mkdir routes
mkdir configs
mkdir version
mkdir cdp-detail
mkdir arp
mkdir mac
mkdir cdp
mkdir lldp
mkdir lldp-detail
mkdir inventory
mkdir bgp-neighbor
mkdir bgp-summary
mkdir interface-status
mkdir port-channel
mkdir int-status
mkdir console
mkdir ip_ssh
mkdir authentication
mkdir authorization
mkdir syslog
mkdir ntp_status
mkdir tacacs
mkdir snmp_server
mkdir nat